### ISSUE TITLE
add XL-Lexeme

### ISSUE THREAD

**Issue by Garrafao** [ChangeIsKey/LSCDBenchmark#40]

**Comment by arshandalili** [comment]
- [ ] Check if we can use the model from [HuggingFace](https://huggingface.co/pierluigic/xl-lexeme) or use it from their [own repository](https://github.com/pierluigic/xl-lexeme)
- [ ] Integrate it to contextual embedders
- [ ] Reproduce [results](https://github.com/Garrafao/durel_system_annotators/issues/30#issuecomment-2003178495) for `DWUG_EN`,  `DWUG_SV`, and `DWUG_DE`
