### ISSUE TITLE
requirements.txt does not reflect all dependencies

### ISSUE THREAD

**Issue by nvanva** [ChangeIsKey/LSCDBenchmark#52]
After installing from requirements.txt running ```python -m unittest tests.integration.test_wic_models.TestWICModels.test_wic_ger_ackergeraet_engpass```
results in ```sentence_transformers``` and ```deepmistake``` dependencies not found.

**Comment by arshandalili** [comment]
`requirements.txt` file has been updated to cover the required libraries.

**Comment by nvanva** [comment]
If I do a fresh clone of the repo and try to install dependencies following the instruction in README after ```pip install -r requirements.txt --find-links https://download.pytorch.org/whl/torch_stable.html``` I get this:
![image](https://github.com/user-attachments/assets/997480a2-9818-49ad-aae0-c454ae3eb181)

**Comment by nvanva** [comment]
Ok, i've solved this problem by removing torchvision from dependencies, we probably don't need it in an NLP benchmark anyway.

**Comment by sachinn12** [comment]
I run this  integration test using the following command:
python -m unittest tests.integration.test_wic_models.TestWICModels.test_wic_eng_simple_plane_afternoon
No dependency errors were found, so I am closing this issue.
